framework:
    secret: '%env(APP_SECRET)%'
    http_method_override: false

    serializer:
        enable_attributes: true

    php_errors:
        log: true
    # Note that the session will be started ONLY if you read or write from it.
    session: true

    #esi: true
    #fragments: true

when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file
